### ISSUE TITLE
frozen: `Failed to execute 'replaceChild' on 'Node': parameter 2 is not of type 'Node'.`

### ISSUE THREAD

**Issue by whilei** [akahuku/wasavi#188]
```
wasavi.js:4976 sequence point with an error: Failed to execute 'replaceChild' on 'Node': parameter 2 is not of type 'Node'.
TypeError: Failed to execute 'replaceChild' on 'Node': parameter 2 is not of type 'Node'.
    at Buffer.emphasisBound (chrome-extension://dgogifpkoilgiofhhhodbodcfgomelhe/frontend/wasavi.js:999:23)
    at setBound (chrome-extension://dgogifpkoilgiofhhhodbodcfgomelhe/frontend/wasavi.js:3075:9)
    at extendBound (chrome-extension://dgogifpkoilgiofhhhodbodcfgomelhe/frontend/wasavi.js:2562:10)
    at chrome-extension://dgogifpkoilgiofhhhodbodcfgomelhe/frontend/wasavi.js:2107:4
    at Generator.next (<anonymous>)
    at run (chrome-extension://dgogifpkoilgiofhhhodbodcfgomelhe/frontend/utils.js:593:20)
    at next (chrome-extension://dgogifpkoilgiofhhhodbodcfgomelhe/frontend/utils.js:584:4)
    at Promise (chrome-extension://dgogifpkoilgiofhhhodbodcfgomelhe/frontend/utils.js:616:3)
    at new Promise (<anonymous>)
    at g.execGenerator (chrome-extension://dgogifpkoilgiofhhhodbodcfgomelhe/frontend/utils.js:582:9)
promise.then.error @ wasavi.js:4976
```
UI stuck looking like:
![screen shot 2017-12-03 at 07 08 39](https://user-images.githubusercontent.com/10228550/33525616-d64520a0-d7f8-11e7-9dd9-2762064c1be3.png)

**Comment by whilei** [comment]
This happens reproducibly when using `v` (for visual mode) on a newline with no characters. The wasavi screen then becomes frozen.
